### ISSUE TITLE
There are no connected tiles, cannot do an optimization. Quitting.

### ISSUE THREAD

**Issue by Alyesca** [PreibischLab/multiview-reconstruction#15]
I am trying to reconstruct a 5 angle multiview dataset of an organoid (ZeissZ.1, 20x, DAPI, Al488, Al546) using nuclei as interest points. The program detects a few thousand points in each angle, but when I try to register the channel the following error comes up: "There are no connected tiles, cannot do an optimization. Quitting."
What am I doing wrong? 
Thanks!
![mv registration issue_b](https://user-images.githubusercontent.com/43123960/45277230-23d0ff80-b50a-11e8-85ab-a6cf613a8bef.png)
![mv registration issue](https://user-images.githubusercontent.com/43123960/45277235-27648680-b50a-11e8-89c2-75e8e9529c7e.png)

**Comment by StephanPreibisch** [comment]
Hi, there a few potential issues:
1) Please visualize the interest points using the Interest Point Explorer (right click) and see if this looks realistic
2) Make sure the calibration (xy/z scaling) is correct - does it look correctly scaled when you rotate it around
3) Are the rotation angles applied correctly? Look along the rotation axis in the window and check if they are more or less in the same orientation (maybe use center-of-mass registration to put them in the more or less same location if it helps) - if not do a) "Apply Transformations ...", Identity on top of calibration b) "Apply Transformations ...", Rigid on top of current view transformation, Rotation around axis, choose Y-Axis and 0, -72, -144, -216, -288 for the respective angles. c) if that doesn't work repeat but with + degrees
4) Which kind of interest point registration do you use? Most likely precise translation-invariant should be a good choice.

Hope this helps,
Stephan
