### ISSUE TITLE
jar file for latest version

### ISSUE THREAD

**Issue by mcahn** [PreibischLab/multiview-reconstruction#2]
We'd like to install the latest Multiview Reconstruction plugin.  Running an update from Fiji gets verison 0.1.5.  I'm not familiar with how to build a jar file from source.  Is a jar of the latest available somewhere?

Thanks,
Matthew Cahn

**Comment by mcahn** [comment]
I added BigStitcher to the list of update sites, and that gave me multiview reconstruction 0.1.13.  Perhaps that's what I was supposed to do.

Matthew

**Comment by StephanPreibisch** [comment]
Hi, yes, please just activate the BigStitcher Update Site in Fiji to get the newest multiview reconstruction version.
