### ISSUE TITLE
How to use the ICP sub-routine ?

### ISSUE THREAD

**Issue by rpadmanabhan** [PreibischLab/multiview-reconstruction#25]
I was interested in using applying your ICP subroutine to a similar but different application that I am working on. Do you think I could take your ICP class and align two point clouds (assuming they are close enough) ? Do you have any pointers on which file(s) I should look at for getting the relevant source code ? 
I was looking at : https://github.com/PreibischLab/multiview-reconstruction/blob/d650e29ea6f0dbafe0b55762c4e6d2027f24b256/src/main/java/net/preibisch/mvrecon/process/pointcloud/icp/ICP.java

Thank You

**Comment by StephanPreibisch** [comment]
Hi, 

check out this class:
https://github.com/PreibischLab/multiview-reconstruction/blob/d650e29ea6f0dbafe0b55762c4e6d2027f24b256/src/main/java/net/preibisch/mvrecon/process/interestpointregistration/pairwise/methods/icp/IterativeClosestPointPairwise.java

An example for non-GUI usage within the bigger context of BigStitcher is here:
https://github.com/PreibischLab/multiview-reconstruction/blob/d650e29ea6f0dbafe0b55762c4e6d2027f24b256/src/main/java/net/preibisch/mvrecon/headless/registration/TestRegistration.java#L176

It is part of the headless package that calls these function. You need to replace the "GeometricHashingPairwise" with "IterativeClosestPointPairwise".

Hope this helps,
Stephan
